/* the person who includes this file must define OP_USAGE */

/*
 * format: OP_USAGE(name, encoding)
 * where encoding is 0 for ABC and 1 for AD
 */

OP_USAGE(RETR, 1)
OP_USAGE(RETK, 1)

OP_USAGE(MOVR, 1)
OP_USAGE(MOVK, 1)

OP_USAGE(NIL, 1)

OP_USAGE(ADDRR, 0)
OP_USAGE(SUBRR, 0)
OP_USAGE(MULRR, 0)
OP_USAGE(DIVRR, 0)

OP_USAGE(ADDRK, 0)
OP_USAGE(SUBRK, 0)
OP_USAGE(MULRK, 0)
OP_USAGE(DIVRK, 0)

OP_USAGE(ADDKR, 0)
OP_USAGE(SUBKR, 0)
OP_USAGE(MULKR, 0)
OP_USAGE(DIVKR, 0)

OP_USAGE(ADDKK, 0)
OP_USAGE(SUBKK, 0)
OP_USAGE(MULKK, 0)
OP_USAGE(DIVKK, 0)

OP_USAGE(CONSRR, 0)
OP_USAGE(CONSRK, 0)
OP_USAGE(CONSKR, 0)
OP_USAGE(CONSKK, 0)

OP_USAGE(CAR, 1)
OP_USAGE(CDR, 1)

OP_USAGE(TABNEW, 1)
OP_USAGE(TABSETRR, 0)
OP_USAGE(TABSETRK, 0)
OP_USAGE(TABSETKR, 0)
OP_USAGE(TABSETKK, 0)
OP_USAGE(TABGETR, 0)
OP_USAGE(TABGETK, 0)

OP_USAGE(EQRR, 0)
OP_USAGE(EQRK, 0)
OP_USAGE(EQKK, 0)

OP_USAGE(LTRR, 0)
OP_USAGE(LTRK, 0)
OP_USAGE(LTKR, 0)
OP_USAGE(LTKK, 0)

OP_USAGE(LTERR, 0)
OP_USAGE(LTERK, 0)
OP_USAGE(LTEKR, 0)
OP_USAGE(LTEKK, 0)

OP_USAGE(JMPF, 1)
OP_USAGE(JMPB, 1)

OP_USAGE(GSETRR, 1)
OP_USAGE(GSETRK, 1)
OP_USAGE(GSETKR, 1)
OP_USAGE(GSETKK, 1)
OP_USAGE(GGETR, 1)
OP_USAGE(GGETK, 1)
